# Generated by Django 4.2.23 on 2025-08-07 22:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0018_currency_directorname_group_shortclass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yurtici_harcirah', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Yurtiçi Harcırah')),
                ('yurtdisi_harcirah', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Yurtdışı Harcırah')),
                ('yol_yardimi', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Yol Yardımı')),
                ('yemek_ticket', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Yemek & Ticket')),
                ('dogum_yardimi', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Doğum Yardımı')),
                ('evlenme_yardimi', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Evlenme Yardımı')),
                ('worker', models.OneToOneField(blank=True, db_column='sicil_no', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='workers.workers', to_field='sicil_no', verbose_name='Sicil No')),
            ],
            options={
                'db_table': 'benefits',
            },
        ),
    ]
