# Generated by Django 4.2.26 on 2025-12-01 21:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sicil_no', models.CharField(max_length=50)),
                ('period', models.DateField()),
                ('aile_yakacak', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('erzak', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('altin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bayram', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dogum_evlenme', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fon', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('harcirah', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('yol_parasi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prim', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_benefits', to='workers.archivedworker')),
            ],
            options={
                'db_table': 'archived_benefits',
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Benefit Period')),
                ('aile_yakacak', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Family')),
                ('erzak', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Provision')),
                ('altin', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gold')),
                ('bayram', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Holiday')),
                ('dogum_evlenme', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Birth & Marriage')),
                ('fon', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Funding')),
                ('harcirah', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subsistence')),
                ('yol_parasi', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fare')),
                ('prim', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Premium')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(db_column='sicil_no', on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='workers.workers', to_field='sicil_no', verbose_name='Sicil No')),
            ],
            options={
                'db_table': 'benefits',
                'ordering': ['worker', 'period'],
                'unique_together': {('worker', 'period')},
            },
        ),
    ]
