# Generated by Django 4.2.23 on 2025-06-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sicil_no', models.CharField(max_length=50, verbose_name='Sicil No')),
                ('name_surname', models.CharField(max_length=100, verbose_name='Adı Soyadı')),
                ('date_of_recruitment', models.DateField(verbose_name='İşe Giriş Tarihi')),
                ('location', models.CharField(max_length=100, verbose_name='Görev Yeri')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cost')),
                ('group', models.CharField(max_length=50, verbose_name='Group')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('directorships', models.CharField(max_length=100, verbose_name='Directorships')),
                ('total_work_days', models.PositiveIntegerField(verbose_name='Total Work Days')),
                ('kidem_alti', models.CharField(max_length=100, verbose_name='Kıdem Altı')),
                ('kidem_tarihi', models.DateField(verbose_name='Kıdem Tarihi')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Gross Salary')),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Bonus')),
                ('account_date', models.DateField(verbose_name='Account Date')),
            ],
        ),
    ]
