# Generated by Django 4.2.26 on 2025-12-07 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_migration_fieldchange'),
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'ordering': ['worker', 'year', 'month']},
        ),
        migrations.AlterUniqueTogether(
            name='benefit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='archivedbenefit',
            name='month',
            field=models.PositiveIntegerField(default=2025, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivedbenefit',
            name='year',
            field=models.PositiveIntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benefit',
            name='month',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benefit',
            name='year',
            field=models.PositiveIntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivedbenefit',
            name='aile_yakacak',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='archivedbenefit',
            name='altin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='archivedbenefit',
            name='bayram',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='archivedbenefit',
            name='dogum_evlenme',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='archivedbenefit',
            name='erzak',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='archivedbenefit',
            name='fon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='archivedbenefit',
            name='harcirah',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='archivedbenefit',
            name='prim',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='archivedbenefit',
            name='yol_parasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='archivedbenefit',
            unique_together={('archived_worker', 'year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='benefit',
            unique_together={('worker', 'year', 'month')},
        ),
        migrations.RemoveField(
            model_name='archivedbenefit',
            name='period',
        ),
        migrations.RemoveField(
            model_name='benefit',
            name='period',
        ),
    ]
