# Generated by Django 4.2.23 on 2025-08-14 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0019_archivedworker_exit_date'),
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='worker',
            field=models.OneToOneField(db_column='sicil_no', on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='workers.workers', to_field='sicil_no', verbose_name='Sicil No'),
        ),
    ]
