# Generated by Django 4.2.23 on 2025-09-18 18:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0019_archivedworker_exit_date'),
        ('benefits', '0002_alter_benefit_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefit',
            name='dogum_yardimi',
        ),
        migrations.RemoveField(
            model_name='benefit',
            name='evlenme_yardimi',
        ),
        migrations.RemoveField(
            model_name='benefit',
            name='yemek_ticket',
        ),
        migrations.RemoveField(
            model_name='benefit',
            name='yol_yardimi',
        ),
        migrations.RemoveField(
            model_name='benefit',
            name='yurtdisi_harcirah',
        ),
        migrations.RemoveField(
            model_name='benefit',
            name='yurtici_harcirah',
        ),
        migrations.AddField(
            model_name='benefit',
            name='aile_yakacak',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Aile & Yakacak'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='altin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Altın'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='bayram',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bayram'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='dogum_evlenme',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Doğum & Evlenme'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='erzak',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Erzak'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='fon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fon'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='harcirah',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Harcırah'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='prim',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prim'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='yol_parasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Yol Parası'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='worker',
            field=models.OneToOneField(db_column='sicil_no', on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='workers.workers', to_field='sicil_no', verbose_name='Sicil No'),
        ),
    ]
