# Generated by Django 4.2.23 on 2025-09-26 05:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0019_archivedworker_exit_date'),
        ('benefits', '0003_remove_benefit_dogum_yardimi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'ordering': ['worker', 'period']},
        ),
        migrations.AddField(
            model_name='benefit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benefit',
            name='period',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Benefit Period'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benefit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='aile_yakacak',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Family'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='altin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gold'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='bayram',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Holiday'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='dogum_evlenme',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Birth & Marriage'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='erzak',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Provision'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='fon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Funding'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='harcirah',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subsistence'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='prim',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Premium'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='worker',
            field=models.ForeignKey(db_column='sicil_no', on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='workers.workers', to_field='sicil_no', verbose_name='Sicil No'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='yol_parasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fare'),
        ),
        migrations.AlterUniqueTogether(
            name='benefit',
            unique_together={('worker', 'period')},
        ),
    ]
