# Generated by Django 4.2.25 on 2025-11-05 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0021_workergrossmonthly_currency'),
        ('benefits', '0004_alter_benefit_options_benefit_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('aile_yakacak', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('erzak', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('altin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bayram', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dogum_evlenme', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fon', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('harcirah', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('yol_parasi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prim', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_benefits', to='workers.archivedworker')),
            ],
        ),
    ]
