# Generated by Django 4.2.25 on 2025-11-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0005_archivedbenefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedbenefit',
            name='sicil_no',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='archivedbenefit',
            table='archived_benefits',
        ),
    ]
