# Generated by Django 4.2.19 on 2025-03-19 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('group', models.CharField(max_length=50)),
                ('sicil_no', models.CharField(max_length=50)),
                ('s_no', models.IntegerField()),
                ('department_short_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('short_class', models.CharField(max_length=50)),
                ('name_surname', models.CharField(max_length=100)),
                ('date_of_recruitment', models.DateTimeField()),
                ('work_class', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=50)),
                ('gross_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
