# Generated by Django 4.2.26 on 2025-12-01 21:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DirectorName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExitReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShortClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sicil_no', models.CharField(max_length=50, unique=True, verbose_name='Sicil No')),
                ('name_surname', models.CharField(max_length=100)),
                ('date_of_recruitment', models.DateTimeField()),
                ('gross_payment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_work_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Total Work Hours')),
                ('update_date_user', models.DateField(blank=True, null=True)),
                ('bonus', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('class_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.classname')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.currency')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.department', verbose_name='Department')),
                ('department_short_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.directorname', verbose_name='Directorships')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.group', verbose_name='Group')),
                ('s_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.costcenter', verbose_name='CostCenter')),
                ('short_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.shortclass', verbose_name='Status')),
                ('work_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.workclass')),
            ],
            options={
                'db_table': 'workers',
            },
        ),
        migrations.CreateModel(
            name='ArchivedWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sicil_no', models.CharField(max_length=50, unique=True, verbose_name='Sicil No')),
                ('name_surname', models.CharField(max_length=100)),
                ('date_of_recruitment', models.DateTimeField()),
                ('gross_payment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_work_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Total Work Hours')),
                ('update_date_user', models.DateField(blank=True, null=True)),
                ('bonus', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('original_id', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('class_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.classname')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.currency')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.department', verbose_name='Department')),
                ('department_short_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.directorname', verbose_name='Directorships')),
                ('exit_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.exitreason')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.group', verbose_name='Group')),
                ('s_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.costcenter', verbose_name='CostCenter')),
                ('short_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.shortclass', verbose_name='Status')),
                ('work_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.workclass')),
            ],
            options={
                'db_table': 'archived_workers',
            },
        ),
        migrations.CreateModel(
            name='WorkerGrossMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.currency')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_gross_salaries', to='workers.workers')),
            ],
            options={
                'db_table': 'worker_gross_monthly',
                'unique_together': {('worker', 'year', 'month')},
            },
        ),
    ]
