# Generated by Django 4.2.20 on 2025-05-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='department_short_name',
            field=models.CharField(max_length=100, verbose_name='Dep.'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='gross_payment',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='workers',
            name='group',
            field=models.CharField(choices=[('PTR', 'PTR'), ('SNY', 'SNY')], max_length=50, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='sicil_no',
            field=models.CharField(max_length=50, verbose_name='Sicil No'),
        ),
    ]
