# Generated by Django 4.2.26 on 2025-12-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workergrossmonthly',
            name='sicil_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
