# Generated by Django 4.2.20 on 2025-05-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_workers_department_short_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='group',
            field=models.CharField(choices=[('PTR', 'PTR'), ('SNY', 'SNY')], default='PTR', max_length=50, verbose_name='Group'),
        ),
    ]
