# Generated by Django 4.2.26 on 2025-12-02 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_workergrossmonthly_sicil_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedWorkerGrossMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sicil_no', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('archived_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_monthly_salaries', to='workers.archivedworker')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.currency')),
            ],
            options={
                'db_table': 'archived_worker_gross_monthly',
            },
        ),
    ]
