# Generated by Django 4.2.20 on 2025-05-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_alter_workers_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='short_class',
            field=models.CharField(choices=[('B', 'B'), ('W', 'W')], max_length=50),
        ),
    ]
