# Generated by Django on 2025-12-06  
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_archivedworkergrossmonthly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workers',
            old_name='gross_payment',
            new_name='gross_payment_hourly',
        ),
        migrations.RenameField(
            model_name='archivedworker',
            old_name='gross_payment',
            new_name='gross_payment_hourly',
        ),
        migrations.RenameField(
            model_name='archivedworkergrossmonthly',
            old_name='gross_salary',
            new_name='gross_salary_hourly',
        ),
        migrations.RenameField(
            model_name='workergrossmonthly',
            old_name='gross_salary',
            new_name='gross_salary_hourly',
        ),
    ]
