# Generated by Django 4.2.26 on 2025-12-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_migration_fieldchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='workergrossmonthly',
            name='gross_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
