# Generated by Django 4.2.20 on 2025-05-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_alter_workers_short_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='short_class',
            field=models.CharField(choices=[('B', 'B'), ('W', 'W')], default='B', max_length=50),
        ),
    ]
