# Generated by Django 4.2.20 on 2025-05-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_alter_workers_work_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='work_class',
            field=models.CharField(choices=[('Quality', 'Quality'), ('Accounting', 'Accounting'), ('Admin', 'Admin'), ('Bohrwerk', 'Bohrwerk'), ('BSA Montage', 'BSA Montage'), ('Design', 'Design'), ('Electrical M.', 'Electrical M.'), ('Export', 'Export'), ('Human Resources', 'Human Resources'), ('Industrial Pump', 'Industrial Pump'), ('IT', 'IT'), ('Maintenance', 'Maintenance'), ('Management', 'Management'), ('Marketing', 'Marketing'), ('Material Planning', 'Material Planning'), ('Metod', 'Metod'), ('Montage', 'Montage'), ('Paint Shop', 'Paint Shop'), ('PM Sales East', 'PM Sales East'), ('PM Sales İzmir', 'PM Sales İzmir'), ('PM Sales Support', 'PM Sales Support'), ('PM Sales West', 'PM Sales West'), ('PM Service Ankara', 'PM Service Ankara'), ('PM Service Asia', 'PM Service Asia'), ('PM Service Europe', 'PM Service Europe'), ('PM Service İzmir', 'PM Service İzmir'), ('PM Service Support', 'PM Service Support'), ('PM Spare Parts', 'PM Spare Parts'), ('Production Planning', 'Production Planning'), ('Project', 'Project'), ('Purchasing', 'Purchasing'), ('SNY Sales Adana', 'SNY Sales Adana'), ('SNY Sales East', 'SNY Sales East'), ('SNY Sales İzmir', 'SNY Sales İzmir'), ('SNY Sales Support', 'SNY Sales Support'), ('SNY Sales West', 'SNY Sales West'), ('SNY Service Ankara', 'SNY Service Ankara'), ('SNY Service Asia', 'SNY Service Asia'), ('SNY Service Europe', 'SNY Service Europe'), ('SNY Service İzmir', 'SNY Service İzmir'), ('SNY Service Support', 'SNY Service Support'), ('SNY Spare Parts', 'SNY Spare Parts'), ('T.Coordination', 'T.Coordination'), ('Test', 'Test'), ('Used Machine', 'Used Machine'), ('W.Robot', 'W.Robot'), ('Warehouse', 'Warehouse'), ('Welding', 'Welding')], default='Select work class', max_length=50),
        ),
    ]
