# Generated by Django 4.2.26 on 2025-12-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_archivedworkergrossmonthly_gross_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedworker',
            name='gross_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='workers',
            name='gross_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='archivedworker',
            name='total_work_hours',
            field=models.DecimalField(blank=True, decimal_places=1, default=225, max_digits=10, null=True, verbose_name='Total Work Hours'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='total_work_hours',
            field=models.DecimalField(blank=True, decimal_places=1, default=225, max_digits=10, null=True, verbose_name='Total Work Hours'),
        ),
    ]
