# Generated by Django 4.2.27 on 2026-01-11 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_archivedworker_gross_payment_workers_gross_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='archivedworker',
            name='location_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.locationname', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='workers',
            name='location_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.locationname', verbose_name='Location'),
        ),
    ]
