# Generated by Django 4.2.27 on 2026-01-18 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_locationname_archivedworker_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workergrossmonthly',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.classname'),
        ),
        migrations.AddField(
            model_name='workergrossmonthly',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.costcenter'),
        ),
        migrations.AddField(
            model_name='workergrossmonthly',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.department'),
        ),
        migrations.AddField(
            model_name='workergrossmonthly',
            name='is_manual_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workergrossmonthly',
            name='location_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.locationname'),
        ),
        migrations.AddField(
            model_name='workergrossmonthly',
            name='short_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.shortclass'),
        ),
        migrations.AddField(
            model_name='workergrossmonthly',
            name='work_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.workclass'),
        ),
    ]
