# Generated by Django 4.2.23 on 2025-06-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_alter_workers_work_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY')], default='TRY', max_length=3),
        ),
        migrations.AlterField(
            model_name='workers',
            name='class_name',
            field=models.CharField(choices=[('Şef', 'Şef'), ('Engelli', 'Engelli'), ('Müdür', 'Müdür'), ('Formen', 'Formen'), ('İşçi', 'İşçi'), ('T.Lideri', 'T.Lideri'), ('Memur', 'Memur')], default='İşçi', max_length=50),
        ),
        migrations.AlterField(
            model_name='workers',
            name='department',
            field=models.CharField(choices=[('Quality', 'Quality'), ('Montage', 'Montage'), ('Technic Office', 'Technic Office'), ('Metod', 'Metod'), ('Spare Parts', 'Spare Parts'), ('S.Structure', 'S.Structure'), ('Production Pln.', 'Production Pln.'), ('Warehouse', 'Warehouse'), ('Sales East', 'Sales East'), ('Sales İzmir', 'Sales İzmir'), ('Service', 'Service'), ('Acco&Finance', 'Acco&Finance'), ('Maintenance', 'Maintenance'), ('Project', 'Project'), ('Marketing', 'Marketing'), ('Sales Support', 'Sales Support'), ('Used Machine', 'Used Machine'), ('Sales West', 'Sales West'), ('Service Support', 'Service Support'), ('Material Pln.', 'Material Pln.'), ('Purchasing', 'Purchasing'), ('HR', 'HR'), ('IT', 'IT'), ('Technic Mng.', 'Technic Mng.'), ('Finance Mng.', 'Finance Mng.'), ('Sales Adana', 'Sales Adana')], default='Quality', max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='department_short_name',
            field=models.CharField(choices=[('T', 'T'), ('S', 'S'), ('F', 'F')], default='T', max_length=100, verbose_name='Directorships'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='short_class',
            field=models.CharField(choices=[('B', 'B'), ('W', 'W')], default='B', max_length=50, verbose_name='Status'),
        ),
    ]
