# Generated by Django 4.2.23 on 2025-06-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_workers_currency_alter_workers_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='group',
            field=models.CharField(blank=True, choices=[('PTR', 'PTR'), ('SNY', 'SNY')], max_length=50, null=True, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='sicil_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='Sicil No'),
        ),
    ]
