# Generated by Django 4.2.27 on 2026-01-18 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_workergrossmonthly_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedworkergrossmonthly',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.classname'),
        ),
        migrations.AddField(
            model_name='archivedworkergrossmonthly',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.costcenter'),
        ),
        migrations.AddField(
            model_name='archivedworkergrossmonthly',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.department'),
        ),
        migrations.AddField(
            model_name='archivedworkergrossmonthly',
            name='short_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.shortclass'),
        ),
        migrations.AddField(
            model_name='archivedworkergrossmonthly',
            name='work_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.workclass'),
        ),
    ]
