# Generated by Django 4.2.23 on 2025-06-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0010_alter_workers_group_alter_workers_sicil_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='group',
            field=models.CharField(blank=True, choices=[('', 'Please select a group'), ('PTR', 'PTR'), ('SNY', 'SNY')], max_length=50, null=True, verbose_name='Group'),
        ),
    ]
