# Generated by Django 4.2.27 on 2026-01-20 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0010_archivedworkergrossmonthly_class_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedworkergrossmonthly',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='archivedworkergrossmonthly',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='archivedworkergrossmonthly',
            name='department',
        ),
        migrations.RemoveField(
            model_name='archivedworkergrossmonthly',
            name='short_class',
        ),
        migrations.RemoveField(
            model_name='archivedworkergrossmonthly',
            name='work_class',
        ),
        migrations.RemoveField(
            model_name='workergrossmonthly',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='workergrossmonthly',
            name='is_manual_override',
        ),
        migrations.AddField(
            model_name='workergrossmonthly',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.group'),
        ),
        migrations.AlterField(
            model_name='workergrossmonthly',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.classname'),
        ),
        migrations.AlterField(
            model_name='workergrossmonthly',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.department'),
        ),
        migrations.AlterField(
            model_name='workergrossmonthly',
            name='location_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.locationname'),
        ),
        migrations.AlterField(
            model_name='workergrossmonthly',
            name='short_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.shortclass'),
        ),
        migrations.AlterField(
            model_name='workergrossmonthly',
            name='work_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.workclass'),
        ),
    ]
