# Generated by Django 4.2.23 on 2025-07-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0011_alter_workers_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
