# Generated by Django 4.2.27 on 2026-01-22 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0011_remove_archivedworkergrossmonthly_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workergrossmonthly',
            name='bonus',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
