# Generated by Django 4.2.27 on 2026-01-22 23:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0012_workergrossmonthly_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedworkergrossmonthly',
            name='bonus',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='archivedworkergrossmonthly',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.classname'),
        ),
        migrations.AddField(
            model_name='archivedworkergrossmonthly',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.department'),
        ),
        migrations.AddField(
            model_name='archivedworkergrossmonthly',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.group'),
        ),
        migrations.AddField(
            model_name='archivedworkergrossmonthly',
            name='location_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.locationname'),
        ),
        migrations.AddField(
            model_name='archivedworkergrossmonthly',
            name='short_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.shortclass'),
        ),
        migrations.AddField(
            model_name='archivedworkergrossmonthly',
            name='work_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.workclass'),
        ),
    ]
