# Generated by Django 4.2.23 on 2025-07-20 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workers', '0012_workers_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='department',
            field=models.CharField(choices=[('Quality', 'Quality'), ('Montage', 'Montage'), ('Technic Office', 'Technic Office'), ('Metod', 'Metod'), ('Spare Parts', 'Spare Parts'), ('S.Structure', 'S.Structure'), ('Production Pln.', 'Production Pln.'), ('Warehouse', 'Warehouse'), ('Sales East', 'Sales East'), ('Sales İzmir', 'Sales İzmir'), ('Service', 'Service'), ('Acco&Finance', 'Acco&Finance'), ('Maintenance', 'Maintenance'), ('Project', 'Project'), ('Marketing', 'Marketing'), ('Sales Support', 'Sales Support'), ('Used Machine', 'Used Machine'), ('Sales West', 'Sales West'), ('Service Support', 'Service Support'), ('Material Pln.', 'Material Pln.'), ('Purchasing', 'Purchasing'), ('HR', 'HR'), ('IT', 'IT'), ('Technic Mng.', 'Technic Mng.'), ('Finance Mng.', 'Finance Mng.'), ('Sales Adana', 'Sales Adana')], default='Quality', max_length=100),
        ),
        migrations.AlterField(
            model_name='workers',
            name='department_short_name',
            field=models.CharField(choices=[('T', 'T'), ('S', 'S'), ('F', 'F')], default='T', max_length=100),
        ),
        migrations.AlterField(
            model_name='workers',
            name='group',
            field=models.CharField(blank=True, choices=[('', 'Please select a group'), ('PTR', 'PTR'), ('SNY', 'SNY')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='short_class',
            field=models.CharField(choices=[('B', 'B'), ('W', 'W')], default='B', max_length=50),
        ),
        migrations.AlterField(
            model_name='workers',
            name='sicil_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='workers',
            table='workers',
        ),
        migrations.CreateModel(
            name='ArchivedWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, choices=[('', 'Please select a group'), ('PTR', 'PTR'), ('SNY', 'SNY')], max_length=50, null=True)),
                ('sicil_no', models.CharField(max_length=50)),
                ('s_no', models.IntegerField()),
                ('department_short_name', models.CharField(choices=[('T', 'T'), ('S', 'S'), ('F', 'F')], default='T', max_length=100)),
                ('department', models.CharField(choices=[('Quality', 'Quality'), ('Montage', 'Montage'), ('Technic Office', 'Technic Office'), ('Metod', 'Metod'), ('Spare Parts', 'Spare Parts'), ('S.Structure', 'S.Structure'), ('Production Pln.', 'Production Pln.'), ('Warehouse', 'Warehouse'), ('Sales East', 'Sales East'), ('Sales İzmir', 'Sales İzmir'), ('Service', 'Service'), ('Acco&Finance', 'Acco&Finance'), ('Maintenance', 'Maintenance'), ('Project', 'Project'), ('Marketing', 'Marketing'), ('Sales Support', 'Sales Support'), ('Used Machine', 'Used Machine'), ('Sales West', 'Sales West'), ('Service Support', 'Service Support'), ('Material Pln.', 'Material Pln.'), ('Purchasing', 'Purchasing'), ('HR', 'HR'), ('IT', 'IT'), ('Technic Mng.', 'Technic Mng.'), ('Finance Mng.', 'Finance Mng.'), ('Sales Adana', 'Sales Adana')], default='Quality', max_length=100)),
                ('short_class', models.CharField(choices=[('B', 'B'), ('W', 'W')], default='B', max_length=50)),
                ('name_surname', models.CharField(max_length=100)),
                ('date_of_recruitment', models.DateTimeField()),
                ('work_class', models.CharField(choices=[('Quality', 'Quality'), ('Accounting', 'Accounting'), ('Admin', 'Admin'), ('Bohrwerk', 'Bohrwerk'), ('BSA Montage', 'BSA Montage'), ('Design', 'Design'), ('Electrical M.', 'Electrical M.'), ('Export', 'Export'), ('Human Resources', 'Human Resources'), ('Industrial Pump', 'Industrial Pump'), ('IT', 'IT'), ('Maintenance', 'Maintenance'), ('Management', 'Management'), ('Marketing', 'Marketing'), ('Material Planning', 'Material Planning'), ('Metod', 'Metod'), ('Montage', 'Montage'), ('Paint Shop', 'Paint Shop'), ('PM Sales East', 'PM Sales East'), ('PM Sales İzmir', 'PM Sales İzmir'), ('PM Sales Support', 'PM Sales Support'), ('PM Sales West', 'PM Sales West'), ('PM Service Ankara', 'PM Service Ankara'), ('PM Service Asia', 'PM Service Asia'), ('PM Service Europe', 'PM Service Europe'), ('PM Service İzmir', 'PM Service İzmir'), ('PM Service Support', 'PM Service Support'), ('PM Spare Parts', 'PM Spare Parts'), ('Production Planning', 'Production Planning'), ('Project', 'Project'), ('Purchasing', 'Purchasing'), ('SNY Sales Adana', 'SNY Sales Adana'), ('SNY Sales East', 'SNY Sales East'), ('SNY Sales İzmir', 'SNY Sales İzmir'), ('SNY Sales Support', 'SNY Sales Support'), ('SNY Sales West', 'SNY Sales West'), ('SNY Service Ankara', 'SNY Service Ankara'), ('SNY Service Asia', 'SNY Service Asia'), ('SNY Service Europe', 'SNY Service Europe'), ('SNY Service İzmir', 'SNY Service İzmir'), ('SNY Service Support', 'SNY Service Support'), ('SNY Spare Parts', 'SNY Spare Parts'), ('T.Coordination', 'T.Coordination'), ('Test', 'Test'), ('Used Machine', 'Used Machine'), ('W.Robot', 'W.Robot'), ('Warehouse', 'Warehouse'), ('Welding', 'Welding')], default='Quality', max_length=50)),
                ('class_name', models.CharField(choices=[('Şef', 'Şef'), ('Engelli', 'Engelli'), ('Müdür', 'Müdür'), ('Formen', 'Formen'), ('İşçi', 'İşçi'), ('T.Lideri', 'T.Lideri'), ('Memur', 'Memur')], default='İşçi', max_length=50)),
                ('gross_payment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY')], default='TRY', max_length=3)),
                ('bonus', models.IntegerField(blank=True, null=True)),
                ('original_id', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'archived_workers',
            },
        ),
    ]
