# Generated by Django 4.2.27 on 2026-01-23 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0013_archivedworkergrossmonthly_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workergrossmonthly',
            name='department_short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workergrossmonthly',
            name='s_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.costcenter'),
        ),
    ]
