# Generated by Django 4.2.23 on 2025-07-31 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0014_alter_archivedworker_bonus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='archivedworker',
            name='group',
            field=models.CharField(choices=[('', 'Please select a group'), ('PTR', 'PTR'), ('SNY', 'SNY')], max_length=50, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='group',
            field=models.CharField(choices=[('', 'Please select a group'), ('PTR', 'PTR'), ('SNY', 'SNY')], max_length=50, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='archivedworker',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.workerclass'),
        ),
        migrations.AlterField(
            model_name='archivedworker',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.department'),
        ),
        migrations.AlterField(
            model_name='archivedworker',
            name='s_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.costcenter'),
        ),
        migrations.AlterField(
            model_name='archivedworker',
            name='work_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.workclass'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.workerclass'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.department'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='s_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.costcenter'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='work_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.workclass'),
        ),
    ]
