# Generated by Django 4.2.23 on 2025-07-31 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0015_costcenter_department_workclass_workerclass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedworker',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='archivedworker',
            name='department',
        ),
        migrations.RemoveField(
            model_name='archivedworker',
            name='department_short_name',
        ),
        migrations.RemoveField(
            model_name='archivedworker',
            name='s_no',
        ),
        migrations.RemoveField(
            model_name='archivedworker',
            name='work_class',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='department',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='department_short_name',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='s_no',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='work_class',
        ),
    ]
