# Generated by Django 4.2.27 on 2026-01-23 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0015_archivedworkergrossmonthly_department_short_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedworkergrossmonthly',
            name='department_short_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.directorname'),
        ),
        migrations.AlterField(
            model_name='workergrossmonthly',
            name='department_short_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.directorname'),
        ),
    ]
