# Generated by Django 4.2.23 on 2025-08-02 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0016_remove_archivedworker_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedworker',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.workerclass'),
        ),
        migrations.AddField(
            model_name='archivedworker',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.department'),
        ),
        migrations.AddField(
            model_name='archivedworker',
            name='department_short_name',
            field=models.CharField(choices=[('T', 'T'), ('S', 'S'), ('F', 'F')], default='T', max_length=100, verbose_name='Directorships'),
        ),
        migrations.AddField(
            model_name='archivedworker',
            name='s_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.costcenter'),
        ),
        migrations.AddField(
            model_name='archivedworker',
            name='work_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.workclass'),
        ),
        migrations.AddField(
            model_name='workers',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.workerclass'),
        ),
        migrations.AddField(
            model_name='workers',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.department'),
        ),
        migrations.AddField(
            model_name='workers',
            name='department_short_name',
            field=models.CharField(choices=[('T', 'T'), ('S', 'S'), ('F', 'F')], default='T', max_length=100, verbose_name='Directorships'),
        ),
        migrations.AddField(
            model_name='workers',
            name='s_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.costcenter'),
        ),
        migrations.AddField(
            model_name='workers',
            name='work_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.workclass'),
        ),
        migrations.AlterField(
            model_name='archivedworker',
            name='group',
            field=models.CharField(choices=[('PTR', 'PTR'), ('SNY', 'SNY')], max_length=50, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='group',
            field=models.CharField(choices=[('PTR', 'PTR'), ('SNY', 'SNY')], max_length=50, verbose_name='Group'),
        ),
    ]
