# Generated by Django 4.2.23 on 2025-08-04 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0017_archivedworker_class_name_archivedworker_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DirectorName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShortClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='WorkerClass',
            new_name='ClassName',
        ),
        migrations.AlterField(
            model_name='archivedworker',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='archivedworker',
            name='s_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.costcenter', verbose_name='CostCenter'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workers',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='s_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.costcenter', verbose_name='CostCenter'),
        ),
        migrations.AlterField(
            model_name='archivedworker',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.currency'),
        ),
        migrations.AlterField(
            model_name='archivedworker',
            name='department_short_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.directorname', verbose_name='Directorships'),
        ),
        migrations.AlterField(
            model_name='archivedworker',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='archivedworker',
            name='short_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.shortclass', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.currency'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='department_short_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.directorname', verbose_name='Directorships'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='short_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.shortclass', verbose_name='Status'),
        ),
    ]
