# Generated by Django 4.2.23 on 2025-08-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0018_currency_directorname_group_shortclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedworker',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
