# Generated by Django 4.2.23 on 2025-10-09 22:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0019_archivedworker_exit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerGrossMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_gross_salaries', to='workers.workers')),
            ],
            options={
                'db_table': 'worker_gross_monthly',
                'unique_together': {('worker', 'year', 'month')},
            },
        ),
    ]
