# Generated by Django 4.2.23 on 2025-10-09 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0020_workergrossmonthly'),
    ]

    operations = [
        migrations.AddField(
            model_name='workergrossmonthly',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.currency'),
        ),
    ]
