# Generated by Django 4.2.25 on 2025-11-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0021_workergrossmonthly_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedworker',
            name='total_work_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Toplam Çalışma Saati'),
        ),
        migrations.AddField(
            model_name='workers',
            name='total_work_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Toplam Çalışma Saati'),
        ),
    ]
