# Generated by Django 4.2.25 on 2025-11-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0022_archivedworker_total_work_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedworker',
            name='total_work_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Toplam Çalışma Saati'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='total_work_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Toplam Çalışma Saati'),
        ),
    ]
