# Generated by Django 4.2.26 on 2025-11-25 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0023_alter_archivedworker_total_work_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='archivedworker',
            name='total_work_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Total Work Hours'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='total_work_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Total Work Hours'),
        ),
        migrations.AddField(
            model_name='archivedworker',
            name='exit_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.exitreason'),
        ),
    ]
