# Generated by Django 4.2.26 on 2025-11-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0024_exitreason_alter_archivedworker_total_work_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedworker',
            name='update_date_user',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workers',
            name='update_date_user',
            field=models.DateField(blank=True, null=True),
        ),
    ]
